docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/Users/vpatankar/Projects/ansibleassessment/docker-based jenkins/jenkins:lts

# -- docker image admin password 1ec3c4a2bd3f4e8687e11e4a4dd0de79
# -- Second password 5b0e599f7db246e6a4a0f92b009f3ef5