---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      instance_type: t2.micro
      security_group: ansible-webserver # Change the security group name here
      image: ami-97785bed # This is an AMI i created myself
      keypair: vinkar_CEP # This is one of my keys that i already have in AWS
      region: us-east-1 # Change the Region
      count: 1
      vpc_subnet: subnet-f43c76db
      vpcid: vpc-7768ab0c
    # Task that will be used to Launch/Create an EC2 Instance
    tasks:

      - name: Create an EC2 key
        ec2_key:
          name: "mykey"
          region: "{{ region }}"
        register: ec2_key

      - name: save private key
        copy:
          content: "{{ ec2_key.key.private_key }}" 
          dest: "./aws-private.pem" 
          mode: 0600
        when: ec2_key.changed

      - name: "Provision an EC2 instance"
        ec2:
          vpc_subnet_id: "{{ vpc_subnet }}"
          key_name: "{{ keypair }}"
          group_id: "{{ security_group }}"
          instance_type: "{{ instance_type }}"
          ec2_region: "{{ region }}"
          image: "{{ image }}"
          wait: true
          count: 1
          instance_tags:
            tool: "ansible"
            env: "test"
            name: "AnsibleEC2Instance"
        register: ec2_info

      - name: Debug ec2_info.instances public_ip
        debug: var=ec2_info.instances[0].public_ip

      - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
        local_action: lineinfile 
                      dest="./hosts" 
                      insertafter="[webserver]" 
                      line="{{ ec2_info.instances[0].public_ip }} ansible_ssh_private_key_file=/ansible-elk-revised/{{ keypair }}.pem"

      # - name: Wait for SSH to come up
      #   local_action: wait_for 
      #                 host={{ item.public_ip }} 
      #                 port=22 
      #                 state=started
      #   with_items: ec2.instances

      # - name: Add tag to Instance(s)
      #   local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      #   with_items: ec2.instances
      #   args:
      #     tags:
      #       Name: webserver

  - name: Install python 2
    hosts: ec2hosts
    remote_user: ubuntu
    sudo: true
    gather_facts: false
    tags: vinkar
    tasks:
      - name: Install Python2 using raw
        raw: sudo apt-get -y install python-simplejson